version : '3.8'
services:
  db-mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: client_management_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 60s
      timeout: 5s
      retries: 5

  backend-app:
    build: ./core-client-management-system
    container_name: springboot_container
    ports:
      - "8080:8080"
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/client_management_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  frontend-app:
    build: ./client-managment-frontend
    container_name: react_container
    ports:
      - "5173:80"
    depends_on:
      - backend-app